# Copyright Broadcom, Inc. All Rights Reserved.
# SPDX-License-Identifier: APACHE-2.0

annotations:
  licenses: Apache-2.0
apiVersion: v2
# Please make sure that version and appVersion are always the same.
appVersion: 2.31.9
description: A Library Helm Chart for grouping common logic between charts. This chart is not deployable by itself. Fork of bitnami/common.
home: https://www.cyrusho.me
icon: https://www.cyrusho.me/favicon.ico
keywords:
  - common
  - helper
  - template
  - function
maintainers:
  - name: Broadcom, Inc. All Rights Reserved.
    url: https://github.com/bitnami/charts
  - name: Cyrus Ho
    url: https://github.com/hlhc/charts
name: common
sources:
  - https://github.com/hlhc/charts/tree/main/charts/common
type: library
version: 2.31.9
