{{- /*
Copyright Cyrus Ho. All Rights Reserved.
SPDX-License-Identifier: APACHE-2.0
*/}}

{{- if and .Values.headplane.enabled .Values.headplane.apiKey.value (not .Values.headplane.apiKey.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-headplane-api-key" (include "common.names.fullname" .) }}
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- include "common.labels.standard" ( dict "customLabels" .Values.commonLabels "context" $ ) | nindent 4 }}
    app.kubernetes.io/component: headplane
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
type: Opaque
data:
  HEADPLANE_OIDC__HEADSCALE_API_KEY: {{ .Values.headplane.apiKey.value | b64enc | quote }}
{{- end }}
