{{- /*
Copyright Cyrus Ho. All Rights Reserved.
SPDX-License-Identifier: APACHE-2.0
*/}}

{{- if .Values.headplane.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-headplane" (include "common.names.fullname" .) }}
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- include "common.labels.standard" ( dict "customLabels" .Values.commonLabels "context" $ ) | nindent 4 }}
    app.kubernetes.io/component: headplane
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
type: Opaque
stringData:
  config.yaml: |
    server:
      host: {{ .Values.headplane.config.server.host | quote }}
      port: {{ .Values.headplane.config.server.port }}
      cookie_secret: {{ include "headscale.headplane.cookieSecret" . | quote }}
      cookie_secure: {{ .Values.headplane.config.server.cookie_secure }}
    headscale:
      url: {{ .Values.headplane.config.headscale.url | quote }}
      config_path: {{ .Values.headplane.config.headscale.config_path | quote }}
      config_strict: {{ .Values.headplane.config.headscale.config_strict }}
    integration:
      kubernetes:
        enabled: {{ .Values.headplane.config.integration.kubernetes.enabled }}
        validate_manifest: {{ .Values.headplane.config.integration.kubernetes.validate_manifest }}
        pod_name: {{ printf "%s-0" (include "common.names.fullname" .) | quote }}
    {{- if .Values.headplane.oidc.enabled }}
    oidc:
      issuer: {{ .Values.headplane.oidc.issuer | quote }}
      disable_api_key_login: {{ .Values.headplane.oidc.disable_api_key_login }}
      token_endpoint_auth_method: {{ .Values.headplane.oidc.token_endpoint_auth_method | quote }}
      redirect_uri: {{ .Values.headplane.oidc.redirect_uri | quote }}
      client_id: {{ .Values.headplane.oidc.client_id | quote }}
    {{- end }}
{{- end }}
