{{- /*
Copyright Cyrus Ho. All Rights Reserved.
SPDX-License-Identifier: APACHE-2.0
*/}}

{{- if .Values.headplane.enabled }}
apiVersion: {{ include "common.capabilities.statefulset.apiVersion" . }}
kind: StatefulSet
metadata:
  name: {{ printf "%s-headplane" (include "common.names.fullname" .) }}
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- include "common.labels.standard" ( dict "customLabels" .Values.commonLabels "context" $ ) | nindent 4 }}
    app.kubernetes.io/component: headplane
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
spec:
  replicas: 1
  podManagementPolicy: OrderedReady
  selector:
    matchLabels: {{- include "common.labels.matchLabels" ( dict "customLabels" .Values.commonLabels "context" $ ) | nindent 6 }}
      app.kubernetes.io/component: headplane
  serviceName: {{ printf "%s-headplane" (include "common.names.fullname" .) }}
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/headplane/secret.yaml") . | sha256sum }}
      labels: {{- include "common.labels.standard" ( dict "customLabels" .Values.commonLabels "context" $ ) | nindent 8 }}
        app.kubernetes.io/component: headplane
    spec:
      shareProcessNamespace: true
      serviceAccountName: {{ include "headscale.headplane.serviceAccountName" . }}
      automountServiceAccountToken: {{ .Values.headplane.serviceAccount.automountServiceAccountToken }}
      {{- if .Values.headplane.containerSecurityContext.enabled }}
      securityContext: {}
      {{- end }}
      containers:
        - name: headplane
          image: {{ template "headscale.headplane.image" . }}
          imagePullPolicy: {{ .Values.headplane.image.pullPolicy }}
          {{- if .Values.headplane.containerSecurityContext.enabled }}
          securityContext: {{- include "common.compatibility.renderSecurityContext" (dict "secContext" .Values.headplane.containerSecurityContext "context" $) | nindent 12 }}
          {{- end }}
          env:
            - name: HEADPLANE_LOAD_ENV_OVERRIDES
              value: "true"
            - name: HEADPLANE_INTEGRATION__KUBERNETES__POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            {{- if .Values.headplane.extraEnvVars }}
            {{- include "common.tplvalues.render" (dict "value" .Values.headplane.extraEnvVars "context" $) | nindent 12 }}
            {{- end }}
          {{- $apiKeySecretName := include "headscale.headplane.apiKeySecretName" . }}
          {{- if or $apiKeySecretName (and .Values.headplane.oidc.enabled .Values.headplane.oidc.existingSecret) .Values.headplane.extraEnvVarsCM .Values.headplane.extraEnvVarsSecret }}
          envFrom:
            {{- if $apiKeySecretName }}
            - secretRef:
                name: {{ $apiKeySecretName }}
            {{- end }}
            {{- if and .Values.headplane.oidc.enabled .Values.headplane.oidc.existingSecret }}
            - secretRef:
                name: {{ .Values.headplane.oidc.existingSecret }}
            {{- end }}
            {{- if .Values.headplane.extraEnvVarsCM }}
            - configMapRef:
                name: {{ include "common.tplvalues.render" (dict "value" .Values.headplane.extraEnvVarsCM "context" $) }}
            {{- end }}
            {{- if .Values.headplane.extraEnvVarsSecret }}
            - secretRef:
                name: {{ include "common.tplvalues.render" (dict "value" .Values.headplane.extraEnvVarsSecret "context" $) }}
            {{- end }}
          {{- end }}
          ports:
            - name: headplane
              containerPort: {{ .Values.headplane.containerPort }}
              protocol: TCP
          {{- if .Values.headplane.resources }}
          resources: {{- toYaml .Values.headplane.resources | nindent 12 }}
          {{- else if ne .Values.headplane.resourcesPreset "none" }}
          resources: {{- include "common.resources.preset" (dict "type" .Values.headplane.resourcesPreset) | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: headscale-config
              mountPath: /etc/headscale
              readOnly: true
            - name: headplane-config
              mountPath: /etc/headplane
              readOnly: true
      volumes:
        - name: headscale-config
          configMap:
            name: {{ include "headscale.configmapName" . }}
        - name: headplane-config
          secret:
            secretName: {{ printf "%s-headplane" (include "common.names.fullname" .) }}
{{- end }}
