# Copyright Cyrus Ho. All Rights Reserved.
# SPDX-License-Identifier: APACHE-2.0

annotations:
  category: Infrastructure
  licenses: Apache-2.0
apiVersion: v2
appVersion: 0.28.0
dependencies:
  - name: common
    repository: oci://ghcr.io/hlhc/charts
    version: 2.x.x
description: Headscale is an open source, self-hosted implementation of the Tailscale control server, with optional headplane web UI.
home: https://headscale.net
icon: https://headscale.net/logo.png
keywords:
  - headscale
  - tailscale
  - vpn
  - wireguard
  - networking
maintainers:
  - name: Cyrus Ho
    url: https://github.com/hlhc
name: headscale
sources:
  - https://github.com/juanfont/headscale
  - https://github.com/juanfont/headscale/pkgs/container/headscale
version: 0.1.3
