{{- /*
Copyright Cyrus Ho. All Rights Reserved.
SPDX-License-Identifier: APACHE-2.0
*/}}

{{- if include "cloudflared.tunnelCredentialsSecretName" . -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cloudflared.tunnelCredentialsSecretName" . }}
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- include "common.labels.standard" ( dict "customLabels" .Values.commonLabels "context" $ ) | nindent 4 }}
    app.kubernetes.io/component: cloudflared
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
type: Opaque
data:
  {{- if empty .Values.cloudflared.tunnelSecrets.existingConfigJsonFileSecret.name }}
  credentials.json: {{ required "cloudflared.tunnelSecrets.base64EncodedConfigJsonFile is required when existingConfigJsonFileSecret is not set. Run: base64 -w 0 ~/.cloudflared/*.json" .Values.cloudflared.tunnelSecrets.base64EncodedConfigJsonFile | quote }}
  {{- end }}
  {{- if empty .Values.cloudflared.tunnelSecrets.existingPemFileSecret.name }}
  cert.pem: {{ required "cloudflared.tunnelSecrets.base64EncodedPemFile is required when existingPemFileSecret is not set. Run: base64 -w 0 ~/.cloudflared/cert.pem" .Values.cloudflared.tunnelSecrets.base64EncodedPemFile | quote }}
  {{- end }}
{{- end }}
